### ISSUE TITLE
最近对直播挺感兴趣，这个代码不全吗？

### ISSUE THREAD

**Issue by hewking** [beautifulSoup/RtmpRecoder#1]
点进项目看了下，发现不全，如果可以的话可以提交下吗，想看看完整的demo 谢啦

**Comment by beautifulSoup** [comment]
@hewking  这个就是直播录制客户端完整的代码，实现了向直播服务器推送h.264编码直播流的功能。如果你需要研究如何搭建服务器和播放直播流，请参考[直播解决方案](http://sixwolf.net/blog/2016/01/29/%E7%9B%B4%E6%92%AD%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-%E6%90%AD%E5%BB%BA%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84%E7%9B%B4%E6%92%AD%E5%B9%B3%E5%8F%B0/)和[如何在网页端和Android端播放直播流](http://sixwolf.net/blog/2016/01/30/%E5%9C%A8%E5%90%84%E7%AB%AF%E5%AE%9E%E7%8E%B0Rtmp%E5%92%8Chls%E6%B5%81%E8%A7%86%E9%A2%91%E7%9A%84%E6%92%AD%E6%94%BE/)这两篇文章，希望能对你有所帮助。另外我所使用的直播服务器目前原作者已经不开源了，所以可以使用我clone的repo[srs](https://github.com/beautifulSoup/srs)
