### ISSUE TITLE
Front Camera Support

### ISSUE THREAD

**Issue by ghost** [beautifulSoup/RtmpRecoder#2]
Hi,

I am trying to display front camera previews.
Currently, I am facing an issue while doing so as it is not able to access front cameras. It connects to only back camera. Is this possible, please help me width code?

**Comment by beautifulSoup** [comment]
hello @mghaffari. I think it's easy and you can do it yourself. Follow this answer [http://stackoverflow.com/questions/2779002/how-to-open-front-camera-on-android-platform](url). Don't forget to add the permission because the permissions of front camera and back are different.
