### ISSUE TITLE
 该如何将屏幕设成直的

### ISSUE THREAD

**Issue by y1787165** [beautifulSoup/RtmpRecoder#5]
您好，我想把屏幕设成直的，于是把

setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

这行砍掉，结果相机的方向就变成反的，我Android 功力不太强，能否麻烦帮忙解惑，感谢万分

**Comment by beautifulSoup** [comment]
稍等，有点事在忙

**Comment by y1787165** [comment]
好的，您慢来！

**Comment by beautifulSoup** [comment]
Camera 这个类的默认展示方向是横向的，它有一个setDisplayOrientation(int degrees) 方法，传入90 度就可以变成纵向的了。不过这个类现在已经被Deprecated 了，这是我很久之前写的一个demo项目，所以一直也没改，建议你换成Camera2

**Comment by beautifulSoup** [comment]
```
public CameraView(Context context, Camera camera) {
            super(context);
            Log.w("camera", "camera view");
            mCamera = camera;
            mHolder = getHolder();
            mHolder.addCallback(CameraView.this);
            mHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);
            mCamera.setPreviewCallback(CameraView.this);
            mCamera.setDisplayOrientation(90);
        }
```

可以加在CameraView的构造函数里面或者获取到Camera对象的时候

**Comment by y1787165** [comment]
您好，我刚刚用这个方法了，的确有转过来，但我如果不使用setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
就无法设置 layout 的大小，试了一阵子都无法成功，想请问问题可能会出在哪边，感谢！

**Comment by y1787165** [comment]
谢谢，我成功试出来了，另外我试了下，这个 view 长宽比似乎要符合16.2比12.4，否则的话影像的比例会有偏差，请问这是正常现象吗

**Comment by beautifulSoup** [comment]
不是  你看add camera view注释下面那段 是根据屏幕长款设置 CameraView的长宽，因为你把Camera设成竖直的了，所以那里的长宽设置倒过来了，你可以相应换下就好了应该。我回家了手上没有环境，你先自己试一下吧。

**Comment by y1787165** [comment]
好的，我先自己研究一阵子，非常感谢大神抽空回答

**Comment by y1787165** [comment]
是这样的，我把这个 view 设成全萤幕了，但是比例跟一般相机相差满多的，我在猜会不会是 camera 抓下来的大小是固定的关系，这边我给个两张图来看看比较清楚

<img width="286" alt="2016-10-10 12 05 47" src="https://cloud.githubusercontent.com/assets/20898610/19221851/2986f75e-8e7e-11e6-96c3-d36948a6850a.png">
<img width="296" alt="2016-10-10 12 05 38" src="https://cloud.githubusercontent.com/assets/20898610/19221852/2d4dc2a0-8e7e-11e6-94bf-0e8f13cebe6b.png">

**Comment by beautifulSoup** [comment]
是的，只支持几种固定尺寸   你可以google一下Android Camera 拉伸问题 上面会有解决方案

**Comment by y1787165** [comment]
非常感谢，研究后解决了
