### ISSUE TITLE
Camera open without release exception

### ISSUE THREAD

**Issue by renyq** [beautifulSoup/RtmpRecoder#6]
` cameraDevice = Camera.open()` 
in  **rtmprecorder\RecordActivity.java(#148)**  suggest modify as 

```
 if (cameraDevice != null) {
            cameraDevice.release();
            cameraDevice = null;
    }
 cameraDevice = Camera.open();

```

because Cameras may be occupied by other applications, so it's best to release it

**Comment by beautifulSoup** [comment]
I changed it like the code below for that the method of Camera.open() will throw a RuntimeException when the camera is occupied by other applications. And I recommend not use the class of Camera that it has been deprecated.
```java

        try {
            cameraDevice = Camera.open();
        } catch (Exception e){
            Log.e(LOG_TAG, "camera open fail, if it's occupied by other applications");
            finish();
            return;
        }
```
