### ISSUE TITLE
 关于 6.0 以上装置问题

### ISSUE THREAD

**Issue by y1787165** [beautifulSoup/RtmpRecoder#7]
你好，我的手机升级到6.0版本之后，在 new FFmpegFrameRecorder 的时候会出现 java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec (如下图)，想请问有没有办法能够解决的感谢。

![0](https://cloud.githubusercontent.com/assets/20898610/21493302/cba382b4-cc45-11e6-8b0e-b6836cdff316.png)

**Comment by y1787165** [comment]
我把 targetSdkVersion 改成 22 后解决了。

**Comment by beautifulSoup** [comment]
ok
